import Head from "next/head"
import styles from "../styles/flex.module.css"
import { useParent } from "@/hooks/useParent"
import Catalogo from "@/Components/Catalogo"
import Spinner from "@/Components/Spinner"

export default function Home() {
	const { Padre, Cargando } = useParent()
	return (
		<>
			<Head>
				<title>Catalogos</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link
					rel="icon"
					href="/favicon.ico"
				/>
			</Head>
			<main>
				<h1 className={styles.h1}>Catalogos</h1>
				<div className={styles.flex}>
					{Cargando && <Spinner />}
					{Padre?.map((padre) => (
						<Catalogo
							key={padre.id}
							padre={padre}
						/>
					))}
				</div>
			</main>
		</>
	)
}
